### ISSUE TITLE
put nav-link underline at the bottom of navbar

### ISSUE THREAD

**Issue by BorisEdison** [pandevs-org/rumblesheetJS-website#2]
![image](https://github.com/user-attachments/assets/f61c03c3-b163-4230-9ff6-f1a6c2a7b1d8)

**Comment by OMIIIEE** [comment]
please assign me

**Comment by OMIIIEE** [comment]
I need little clarification on whether to underline navlinks when hover below the navbar like this 
![image](https://github.com/user-attachments/assets/3289bf31-28ba-4c50-984a-6f82d5e31a73)

or to permanently underline navlinks inside the navbar or below the navbar

**Comment by BorisEdison** [comment]
this is how the underline should look 

![image](https://github.com/user-attachments/assets/f6f6697a-22ec-48ce-8a53-751222451773)

it should be active when we are on that particular tab and also on hover it should be active on other tabs
